services:
  backend:
    build: ./backend
    restart: unless-stopped
    environment:
      - TZ=America/New_York
    volumes:
      - dictionary_cache:/root/.pyspellchecker
      - data_volume:/app/data

  frontend:
    build: ./frontend
    restart: unless-stopped
    environment:
      - PUBLIC_BACKEND_URL=${PUBLIC_BACKEND_URL}
    depends_on:
      - backend

volumes:
  dictionary_cache:
  data_volume:
